import Footer from "@/components/footer";
import "./globals.css";
import Header from "@/components/header";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Berat Dimen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <div className="generalBody">
          <Header />
          <div className="general">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
